### ISSUE TITLE
yowasp-yosys errors with functions

### ISSUE THREAD

**Issue by udif** [TinyTapeout/tt08-verilog-template#14]
It seems that the bundled `yowasp-yosys` has some issues with functions. Given the code:
```
module t;

function integer min(input integer x, input integer y);
  return (x < y) ? x : y;
  //min = (x < y) ? x : y;
endfunction

endmodule
```
The yowasp-yosys synthesis output is:
```

 /----------------------------------------------------------------------------\
 |  yosys -- Yosys Open SYnthesis Suite                                       |
 |  Copyright (C) 2012 - 2024  Claire Xenia Wolf <claire@yosyshq.com>         |
 |  Distributed under an ISC-like license, type "license" to see terms        |
 \----------------------------------------------------------------------------/
 Yosys 0.42 (git sha1 9b6afcf3f, ccache clang 14.0.0-1ubuntu1.1 -Os -flto -flto)

-- Parsing `p.sv' using frontend ` -sv' --

1. Executing Verilog-2005 frontend: p.sv
Parsing SystemVerilog input from `p.sv' to AST representation.
p.sv:4: ERROR: syntax error, unexpected '?', expecting ';'
```

Commenting out the `return` statement and using the other form (assigning the function name) works fine.
The same code works fine on regular yosys 0.37 as found on [edaplayground.com](edaplayground.com)

**Comment by urish** [comment]
Sounds like an issue for yosys?

**Comment by udif** [comment]
I was going to comment that it might be an issue with the specific build tt is using, but I just rebuilt the master Yosys branch and it fails the same way.

**Comment by udif** [comment]
OK, closing this issue. It seems that `return` is a SystemVerilog extension, not part of IEEE1364-2005, and the base Yosys parser doesn't handle it. I am guessing that the version [edaplayground.com](edaplayground.com) is hosting is using the commercial verific front end.
